# Generated by Django 5.2.3 on 2025-06-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tooltip',
        ),
    ]
