# Generated by Django 5.2.3 on 2025-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sale', models.CharField(blank=True, max_length=10)),
                ('isnew', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('price_new', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_old', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('topselling', models.BooleanField(default=False)),
            ],
        ),
    ]
